axis_limits:
  x_min: -99
  x_max: 99
  y_min: -196
  y_max: 51
  z_min: -147.625
  z_max: 102
reference_xy:
  x: 0
  y: -72.5
z_reference:
  bed_contact: -147.625
  safe_floor: -147.425
gantry_base_exception:
  z_min: -147.625
  z_max: -123.625
