cmake_minimum_required(VERSION 3.8)
project(printer_initialization)

find_package(ament_cmake REQUIRED)
find_package(rclcpp REQUIRED)
find_package(sensor_msgs REQUIRED)
find_package(urdf REQUIRED)
find_package(printer_initialization_msgs REQUIRED)
find_package(yaml-cpp REQUIRED)
find_package(fcl REQUIRED)

add_executable(collision_monitor_node src/collision_monitor_node.cpp)
target_compile_features(collision_monitor_node PUBLIC cxx_std_17)
ament_target_dependencies(collision_monitor_node rclcpp printer_initialization_msgs)
target_link_libraries(collision_monitor_node yaml-cpp)

add_executable(fcl_collision_detector_node src/fcl_collision_detector_node.cpp)
target_compile_features(fcl_collision_detector_node PUBLIC cxx_std_17)
ament_target_dependencies(fcl_collision_detector_node rclcpp sensor_msgs urdf printer_initialization_msgs)
target_link_libraries(fcl_collision_detector_node fcl)

add_executable(initialization_motion_node src/initialization_motion_node.cpp)
target_compile_features(initialization_motion_node PUBLIC cxx_std_17)
ament_target_dependencies(initialization_motion_node rclcpp sensor_msgs printer_initialization_msgs)

add_executable(initialization_manager_node src/initialization_manager_node.cpp)
target_compile_features(initialization_manager_node PUBLIC cxx_std_17)
ament_target_dependencies(initialization_manager_node rclcpp sensor_msgs printer_initialization_msgs)
target_link_libraries(initialization_manager_node yaml-cpp)

install(TARGETS collision_monitor_node fcl_collision_detector_node initialization_motion_node initialization_manager_node DESTINATION lib/${PROJECT_NAME})

ament_package()
