<?xml version="1.0"?>
<package format="3">
  <name>printer_initialization</name>
  <version>0.1.0</version>
  <description>Collision monitoring support for printer initialization.</description>
  <maintainer email="wjd@example.com">wjd</maintainer>
  <license>Apache-2.0</license>
  <buildtool_depend>ament_cmake</buildtool_depend>
  <depend>rclcpp</depend>
  <depend>sensor_msgs</depend>
  <depend>urdf</depend>
  <depend>printer_initialization_msgs</depend>
  <exec_depend>yaml-cpp</exec_depend>
  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
