//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Voron24
{
    [Serializable]
    public class ExtrusionPointMsg : Message
    {
        public const string k_RosMessageName = "voron24_msgs/ExtrusionPoint";
        public override string RosMessageName => k_RosMessageName;

        //  압출 궤적 1점. ROS2 -> Unity, 이벤트 기반.
        //  position 은 bed_origin 프레임 기준, 단위 m.
        //  extruding=false 이면 travel move (선을 끊으라는 신호).
        public Std.HeaderMsg header;
        public Geometry.PointMsg position;
        //  압출 폭 [m]
        public float width;
        //  레이어 높이 [m]
        public float height;
        public bool extruding;
        public uint layer;

        public ExtrusionPointMsg()
        {
            this.header = new Std.HeaderMsg();
            this.position = new Geometry.PointMsg();
            this.width = 0.0f;
            this.height = 0.0f;
            this.extruding = false;
            this.layer = 0;
        }

        public ExtrusionPointMsg(Std.HeaderMsg header, Geometry.PointMsg position, float width, float height, bool extruding, uint layer)
        {
            this.header = header;
            this.position = position;
            this.width = width;
            this.height = height;
            this.extruding = extruding;
            this.layer = layer;
        }

        public static ExtrusionPointMsg Deserialize(MessageDeserializer deserializer) => new ExtrusionPointMsg(deserializer);

        private ExtrusionPointMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            this.position = Geometry.PointMsg.Deserialize(deserializer);
            deserializer.Read(out this.width);
            deserializer.Read(out this.height);
            deserializer.Read(out this.extruding);
            deserializer.Read(out this.layer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.position);
            serializer.Write(this.width);
            serializer.Write(this.height);
            serializer.Write(this.extruding);
            serializer.Write(this.layer);
        }

        public override string ToString()
        {
            return "ExtrusionPointMsg: " +
            "\nheader: " + header.ToString() +
            "\nposition: " + position.ToString() +
            "\nwidth: " + width.ToString() +
            "\nheight: " + height.ToString() +
            "\nextruding: " + extruding.ToString() +
            "\nlayer: " + layer.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
