//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Voron24
{
    [Serializable]
    public class PrinterStatusMsg : Message
    {
        public const string k_RosMessageName = "voron24_msgs/PrinterStatus";
        public override string RosMessageName => k_RosMessageName;

        //  프린터 상태. ROS2 -> Unity, 5 Hz.
        //  계약 00_interface_contract.md section 5
        public Std.HeaderMsg header;
        //  "idle" | "printing" | "paused" | "error"
        public string state;
        //  0.0 ~ 1.0
        public float progress;
        public uint current_layer;
        public uint total_layers;
        public string filename;

        public PrinterStatusMsg()
        {
            this.header = new Std.HeaderMsg();
            this.state = "";
            this.progress = 0.0f;
            this.current_layer = 0;
            this.total_layers = 0;
            this.filename = "";
        }

        public PrinterStatusMsg(Std.HeaderMsg header, string state, float progress, uint current_layer, uint total_layers, string filename)
        {
            this.header = header;
            this.state = state;
            this.progress = progress;
            this.current_layer = current_layer;
            this.total_layers = total_layers;
            this.filename = filename;
        }

        public static PrinterStatusMsg Deserialize(MessageDeserializer deserializer) => new PrinterStatusMsg(deserializer);

        private PrinterStatusMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.state);
            deserializer.Read(out this.progress);
            deserializer.Read(out this.current_layer);
            deserializer.Read(out this.total_layers);
            deserializer.Read(out this.filename);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.state);
            serializer.Write(this.progress);
            serializer.Write(this.current_layer);
            serializer.Write(this.total_layers);
            serializer.Write(this.filename);
        }

        public override string ToString()
        {
            return "PrinterStatusMsg: " +
            "\nheader: " + header.ToString() +
            "\nstate: " + state.ToString() +
            "\nprogress: " + progress.ToString() +
            "\ncurrent_layer: " + current_layer.ToString() +
            "\ntotal_layers: " + total_layers.ToString() +
            "\nfilename: " + filename.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
