//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Voron24
{
    [Serializable]
    public class PrinterCommandMsg : Message
    {
        public const string k_RosMessageName = "voron24_msgs/PrinterCommand";
        public override string RosMessageName => k_RosMessageName;

        //  Unity -> ROS2 조작 명령.
        //  command 별 args 규약:
        //    "jog"        args = [dx, dy, dz]  (mm)
        //    "home"       args = []            (payload 로 "XYZ" 등 축 지정 가능)
        //    "pause"      args = []
        //    "resume"     args = []
        //    "stop"       args = []
        //    "load_gcode" payload = 파일 절대경로
        //    "set_speed"  args = [scale]
        public string command;
        public float[] args;
        public string payload;

        public PrinterCommandMsg()
        {
            this.command = "";
            this.args = new float[0];
            this.payload = "";
        }

        public PrinterCommandMsg(string command, float[] args, string payload)
        {
            this.command = command;
            this.args = args;
            this.payload = payload;
        }

        public static PrinterCommandMsg Deserialize(MessageDeserializer deserializer) => new PrinterCommandMsg(deserializer);

        private PrinterCommandMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.command);
            deserializer.Read(out this.args, sizeof(float), deserializer.ReadLength());
            deserializer.Read(out this.payload);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.command);
            serializer.WriteLength(this.args);
            serializer.Write(this.args);
            serializer.Write(this.payload);
        }

        public override string ToString()
        {
            return "PrinterCommandMsg: " +
            "\ncommand: " + command.ToString() +
            "\nargs: " + System.String.Join(", ", args.ToList()) +
            "\npayload: " + payload.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
